apiVersion: 1

datasources:
  - name: Pipeline API
    uid: PIPELINE_API
    type: grafana-json-datasource
    access: proxy
    url: http://api:8081/api/analytics/grafana
    isDefault: false
    version: 1
    editable: false
