services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8081:8081"
    environment:
      CHDB_DATA_PATH: /data
      CHDB_TABLE: events
    volumes:
      - api-data:/data

  ecommerce:
    build:
      context: ..
      dockerfile: ecommerce/Dockerfile
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  api-data:
