services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8081:8081"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_DB: default
      CLICKHOUSE_TABLE: events
    depends_on:
      clickhouse:
        condition: service_started

  ecommerce:
    build:
      context: ..
      dockerfile: ecommerce/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  clickhouse-data:
